services:
  frontend:
    container_name: rrbuddy_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    container_name: rrbuddy_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      - postgres  

  postgres:
    container_name: rrbbudy_postgres
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database  
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./database/populate.sql:/docker-entrypoint-initdb.d/populate.sql

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
